# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aService(object):
    def setupUi(self, aService):
        aService.setObjectName("aService")
        aService.resize(341, 337)
        self.verticalLayout = QtWidgets.QVBoxLayout(aService)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(aService)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.typeBox = QtWidgets.QComboBox(aService)
        self.typeBox.setObjectName("typeBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.typeBox)
        self.label_2 = QtWidgets.QLabel(aService)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.bindPort = QtWidgets.QSpinBox(aService)
        self.bindPort.setMinimum(1)
        self.bindPort.setMaximum(65535)
        self.bindPort.setProperty("value", 5000)
        self.bindPort.setObjectName("bindPort")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bindPort)
        self.label_3 = QtWidgets.QLabel(aService)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.targetIP = QtWidgets.QLineEdit(aService)
        self.targetIP.setObjectName("targetIP")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.targetIP)
        self.label_4 = QtWidgets.QLabel(aService)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.targetPort = QtWidgets.QSpinBox(aService)
        self.targetPort.setMinimum(1)
        self.targetPort.setMaximum(65535)
        self.targetPort.setProperty("value", 5001)
        self.targetPort.setObjectName("targetPort")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.targetPort)
        self.label_5 = QtWidgets.QLabel(aService)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.workerNumber = QtWidgets.QSpinBox(aService)
        self.workerNumber.setMinimum(10)
        self.workerNumber.setMaximum(1000)
        self.workerNumber.setObjectName("workerNumber")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.workerNumber)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create = QtWidgets.QPushButton(aService)
        self.create.setObjectName("create")
        self.horizontalLayout.addWidget(self.create)
        self.cancel = QtWidgets.QPushButton(aService)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(aService)
        QtCore.QMetaObject.connectSlotsByName(aService)

    def retranslateUi(self, aService):
        _translate = QtCore.QCoreApplication.translate
        aService.setWindowTitle(_translate("aService", "Add Service"))
        self.label.setText(_translate("aService", "Type"))
        self.label_2.setText(_translate("aService", "Bind Port"))
        self.label_3.setText(_translate("aService", "Target IP"))
        self.label_4.setText(_translate("aService", "Target Port"))
        self.label_5.setText(_translate("aService", "Number of Workers"))
        self.create.setText(_translate("aService", "Create"))
        self.cancel.setText(_translate("aService", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aService = QtWidgets.QWidget()
    ui = Ui_aService()
    ui.setupUi(aService)
    aService.show()
    sys.exit(app.exec_())
