# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dService(object):
    def setupUi(self, dService):
        dService.setObjectName("dService")
        dService.resize(420, 168)
        self.verticalLayout = QtWidgets.QVBoxLayout(dService)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dService)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(dService)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dButton = QtWidgets.QPushButton(dService)
        self.dButton.setObjectName("dButton")
        self.horizontalLayout.addWidget(self.dButton)
        self.cButton = QtWidgets.QPushButton(dService)
        self.cButton.setObjectName("cButton")
        self.horizontalLayout.addWidget(self.cButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dService)
        QtCore.QMetaObject.connectSlotsByName(dService)

    def retranslateUi(self, dService):
        _translate = QtCore.QCoreApplication.translate
        dService.setWindowTitle(_translate("dService", "Delete Service"))
        self.label.setText(_translate("dService", "Choose the service to delete:"))
        self.dButton.setText(_translate("dService", "Delete"))
        self.cButton.setText(_translate("dService", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dService = QtWidgets.QWidget()
    ui = Ui_dService()
    ui.setupUi(dService)
    dService.show()
    sys.exit(app.exec_())
